name: dafr-mcview
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core
  - r-base>=4.3,<4.4
  - julia>=1.10
  # System libraries
  - libcurl
  - hdf5
  - openssl
  - libxml2
  - zlib
  - bzip2
  - xz
  - libgit2
  - cairo
  - harfbuzz
  - fribidi
  - freetype
  - fontconfig
  - libpng
  - libtiff
  - gsl
  # R build tools
  - r-devtools
  - r-remotes
  # dafr dependencies
  - r-cli
  - r-juliacall
  - r-matrix
  - r-tibble
  - r-tidyr
  # MCView dependencies (from conda-forge/bioconda)
  - r-anndata
  - r-shiny>=1.6.0
  - r-ggplot2
  - r-dplyr
  - r-purrr
  - r-rlang
  - r-glue
  - r-htmltools
  - r-cachem
  - r-forcats>=1.0.0
  - r-fs
  - r-rmarkdown
  - r-colourpicker
  - r-circlize
  - r-cowplot>=1.2.0
  - r-dt
  - r-furrr
  - r-future
  - r-ggforce
  - r-fastcluster
  - r-golem
  - r-markdown>=1.3.0
  - r-matrixstats
  - r-pkgload
  - r-plotly>=4.9.3
  - r-promises
  - r-qs
  - r-rclipboard
  - r-scales
  - r-shinyjs
  - r-shinyjqui
  - r-shinycssloaders
  - r-shinydashboard
  - r-shinydashboardplus>=2.0.0
  - r-shinywidgets>=0.7.0
  - r-shinybusy
  - r-viridis
  - r-vegan
  - r-yaml
  - r-zip
  - r-ggtext>=0.1.0
  - r-waiter
  - r-umap
  - r-gert
  # Additional R packages commonly needed
  - r-withr
  - r-testthat
